---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule -v test
  retry: 1
  parallel:
    matrix:
      - image: "ubuntu"
        tag: "22.04"
      - image: "ubuntu"
        tag: "21.04"
      - image: "ubuntu"
        tag: "20.04"
      - image: "ubuntu"
        tag: "18.04"
      - image: "centos"
        tag: "centos7"
      - image: "centos"
        tag: "centos8"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"

testing:
  script:
    - image=${image} tag=${tag} molecule -v test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "enterpriselinux"
        tag: "7"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"

galaxy:
  script:
    - ansible-galaxy role info buluma.sentry

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.sentry
  retry: 1
  parallel:
    matrix:
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "enterpriselinux"
        tag: "7"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"
