---
roles:
  - name: buluma.bootstrap
  - name: Duologic.postgresql_repository
  - name: geerlingguy.redis
  - name: Duologic.postgresql_repository
  - name: geerlingguy.postgresql
  - name: Duologic.sentry
collections:
  - name: community.general
