---
roles:
  - name: buluma.bootstrap
  - name: Duologic.postgresql_repository
  - name: geerlingguy.redis
  - name: geerlingguy.postgresql
  - name: Duologic.sentry  # TODO: localise on release
  - name: buluma.buildtools
  - name: buluma.cron
collections:
  - name: community.general
