---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    - role: buluma.buildtools
    - role: buluma.cron
    - role: duologic.postgresql_repository
    - role: geerlingguy.redis
    - role: geerlingguy.postgresql
    - role: duologic.sentry
